---
title: "Lameness Processing and Report"
editor: source
format: 
 html:
   embed-resources: true
   toc: true
   toc-location: left
execute:
    echo: false
    message: false
    warning: false
---

```{r}
library(tidyverse)
library(arrow)
library(dtplyr)
library(DT)
library(gt)
library(flextable)
library(gtsummary)

source('functions/fxn_dt_base.R') #functions to parse remarks and protocols

source('functions/fxn_load_os_fxns.R')
fxn_load_os_fxns()


# load animals to get animal level data
animals <-read_parquet('data/intermediate_files/animals.parquet') |> 
   select(location_event = location_list,
          id_animal, id,  date_birth, date_left, date_sold, date_died)

# load events
events_formatted<-read_parquet('data/intermediate_files/events_formatted.parquet') |> 
   filter(event %in% c("LAME", "FOOTRIM")) |>  
  left_join(animals)




# for data checks
summarize_events<-events_formatted |> 
  group_by(farm = location_event, event, protocols_remaining_after_numbers1, 
           remark_letters1
           ) |> 
  summarize(count_rows=sum(n()))|>
  ungroup()%>%
  mutate(event_type = factor(protocols_remaining_after_numbers1), 
         remark_type = factor(remark_letters1), 
         Event = factor(event),
         event_type = if_else(is.na(event_type),
                              "No Protocol Recorded", event_type),
         remark_type = if_else(is.na(remark_type), "No Remark Recorded",
                               remark_type)
         )

```

## Check out what Lesions are being reported

### Protocol Data

```{r}
#| fig-height: 12
# count y vars

facet_order <- summarize_events %>%
  group_by(farm, event_type) %>%
  summarise(n_y = n_distinct(event)) %>%
  arrange(desc(n_y)) %>%  # Order by most y categories
  pull(event_type)

# order events
summarize_events <- summarize_events %>%
  mutate(event_type = fct_reorder(event_type, count_rows, .fun = sum, .desc = FALSE)) 

  ggplot(summarize_events)+
  geom_bar(aes(x = event_type,
               y = count_rows, fill = event_type), stat = "identity")+
  #facet_wrap(factor(event, levels = facet_order) ~., scales = 'free')+
    facet_wrap(vars(farm, event), ncol = 2 , scales = "free")+
  coord_flip()+
  scale_fill_viridis_d()+
  theme_minimal()+
  labs(x = "",
       y = "Row Count")+
  theme(legend.position = "none",
        # axis.text.y = element_text(size = 6)
        )
```

### Remarks

Description of top 10 remarks recorded, Other is combined remaining remarks

```{r}
#| fig-height: 8

facet_order <- summarize_events %>%
  group_by(farm, remark_type) %>%
  summarise(n_y = n_distinct(event)) %>%
  arrange(desc(n_y)) %>%  # Order by most y categories
  pull(remark_type)

# order events
summarize_events <- summarize_events %>%
  # mutate(event_type = fct_reorder(remark_type, 
  #                                 count_rows, .fun = sum, .desc = FALSE)) 
  mutate(remark_type = fct_lump_n(remark_type,
                                 n = 10,
                                 ties.method = "random" ))
  

  ggplot(summarize_events)+
  geom_bar(aes(x = remark_type,
               y = count_rows, fill = remark_type), stat = "identity")+
  #facet_wrap(factor(event, levels = facet_order) ~., scales = 'free')+
    facet_wrap(vars(farm, event), ncol = 2, scales = "free")+
  coord_flip()+
  scale_fill_viridis_d()+
  theme_minimal()+
  labs(x = "",
       y = "Row Count")+
  theme(legend.position = "none",
        # axis.text.y = element_text(size = 6)
        )
```

# Process lesion data

```{r}
#| label: process_lesion_data

all_lesions <- c("dd", "footrot", 'wld', "sole_ulcer","injury", 
                   "cork", "other", "hemorrhage",
                   "sole_fracture", "toe_ulcer", "thin",
                   "inf", "noninf", "toe", "axial", "lesion")
  
diseases <- c("inf", "noninf", "lesion")
  
  lame_data <- events_formatted |> 
    select(location_event, id_animal, id, date_birth, date_fresh,lact_number, 
           lact_group, lact_group_5,
           date_archived, date_event, date_left, date_sold, date_died,
           event, 
           remark_letters1, protocols_letters1, location_event) |> 
    mutate(protocols_letters1 = if_else(protocols_letters1 %in% ("MAINTENANCE"),
                                        "Trim Only", protocols_letters1)) |>
    fxn_code_lesions(protocol_var = protocols_letters1,
                     remark_var = remark_letters1) |> 
    # fix ab and NA issues
    filter(!is.na(trimonly)) |>
    mutate(noninf = case_when(
      other == 1 & str_detect(protocols_letters1, "Ab") ~ 1,
      .default = noninf),
      # remove other catergory if abscess is found
      other = case_when(
        other == 1 & str_detect(protocols_letters1, "Ab") ~ 0,
        .default = other)
    ) |> 
    fxn_collapse_lesions(lesions = all_lesions) |> 
    fxn_trim_vars(location_event, id_animal,
                  date_var = date_event,
                  trimonly_var = trimonly) |> 
    fxn_dz_status(disease_cols = diseases,
                  event_filter = trimonly == 0)

# save lameness files

  write_parquet(lame_data, 
                'data/intermediate_files/lame_data.parquet')  



```
move to tioga date

```{r}

move <- read_parquet('data/intermediate_files/events_formatted.parquet') |> 
  filter(event %in% c("MOVE") & location_event == "41464500") |>
  # remove zeros form remarks
  mutate(from_pen = as.numeric(str_remove_all(remark_numbers1, "0")),
         to_pen = as.numeric(str_remove_all(remark_numbers2, "0"))
         )|>
  filter(from_pen < 10 & to_pen > 70 & date_event > ymd("20251101")) |>
  mutate(date_move = date_event) |>
  left_join(animals |> 
              select(id_animal, date_birth, date_left, date_sold, date_died),
            by = c("id_animal", "date_birth")) |>
  select(c(id_animal, id, date_event, from_pen, to_pen, date_move,
         date_birth, date_left, date_sold, date_died))

write_parquet(move, 
              'data/intermediate_files/move_tioga.parquet')
  
  

```


